module.exports = {
  TWITTER_USER: process.env.TWITTER_USER || '',
  TWITTER_CONSUMERKEY: process.env.TWITTER_CONSUMERKEY || '',
  TWITTER_CONSUMERSECRET: process.env.TWITTER_CONSUMERSECRET || '',
  TWITTER_OAUTHACCESSTOKEN: process.env.TWITTER_OAUTHACCESSTOKEN || '',
  TWITTER_OAUTHACCESSTOKENSECRET: process.env.TWITTER_OAUTHACCESSTOKENSECRET || ''
}
